### ISSUE TITLE
创建项目，名称为中文时，后台报错

### ISSUE THREAD

**Issue by Contentment** [HttpRunner/HttpRunnerManager#109]
2018-09-27 13:08:27,230 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/add_project/
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/python/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/python/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/python/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/python/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/python/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)

**Comment by q88535448** [comment]
python3环境没有这个问题啊，我们的项目名称就是中文

**Comment by Contentment** [comment]
数据库编码错误导致
