### ISSUE TITLE
运行用例报httprunner.exceptions.ParamsError: base url missed!

### ISSUE THREAD

**Issue by jimmysm** [HttpRunner/HttpRunnerManager#116]
正常配置baidu.com 执行用例 测试结果报错 麻烦看下 是哪里配置有问题吗
具体报错信息
Traceback (most recent call last):
  File "C:\Users\min.shi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httprunner\task.py", line 27, in runTest
    self.test_runner.run_test(self.testcase_dict)
  File "C:\Users\min.shi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httprunner\runner.py", line 167, in run_test
    **parsed_request
  File "C:\Users\min.shi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httprunner\client.py", line 128, in request
    url = self._build_url(url)
  File "C:\Users\min.shi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httprunner\client.py", line 52, in _build_url
    raise ParamsError("base url missed!")
httprunner.exceptions.ParamsError: base url missed!

![image](https://user-images.githubusercontent.com/35726582/48336997-aa39c700-e69c-11e8-9235-230a7cb6e2a9.png)

**Comment by rolandluo** [comment]
你填写” http://www.baidu.com“
