### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by JoffreyN** [HttpRunner/HttpRunnerManager#127]
2019-01-10 14:28:11,099 [django.request:228] [log:log_response] [ERROR]- Internal Server Error: /api/run_test/
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Program Files\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Program Files\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Users\ZP\Desktop\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "E:\Users\ZP\Desktop\HttpRunnerManager\ApiManager\views.py", line 39, in wrapper
    return func(request, *args, **kwargs)
  File "E:\Users\ZP\Desktop\HttpRunnerManager\ApiManager\views.py", line 238, in run_test
    runner.summary = timestamp_to_datetime(runner.summary, type=False)
AttributeError: can't set attribute
ERROR:django.request:Internal Server Error: /api/run_test/
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Program Files\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Program Files\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Users\ZP\Desktop\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "E:\Users\ZP\Desktop\HttpRunnerManager\ApiManager\views.py", line 39, in wrapper
    return func(request, *args, **kwargs)
  File "E:\Users\ZP\Desktop\HttpRunnerManager\ApiManager\views.py", line 238, in run_test
    runner.summary = timestamp_to_datetime(runner.summary, type=False)
AttributeError: can't set attribute

**Comment by SLG061** [comment]
请问问题解决了吗，我也遇到了同样的问题，想问下解决方法
