### ISSUE TITLE
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

### ISSUE THREAD

**Issue by asdf2014** [HttpRunner/HttpRunnerManager#134]
(http_runner)  benedictjin@BenedictJin  /code/HttpRunnerManager   master ●  python manage.py celery -A HttpRunnerManager worker --loglevel=info
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/apps/python/http_runner/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/apps/python/http_runner/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/apps/python/http_runner/lib/python3.6/site-packages/djcelery/management/commands/celery.py", line 21, in run_from_argv
    ['{0[0]} {0[1]}'.format(argv)] + argv[2:],
  File "/apps/python/http_runner/lib/python3.6/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/apps/python/http_runner/lib/python3.6/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    self.on_concurrency_setup()
  File "/apps/python/http_runner/lib/python3.6/site-packages/celery/bin/celery.py", line 833, in on_concurrency_setup
    self.load_extension_commands()
  File "/apps/python/http_runner/lib/python3.6/site-packages/celery/bin/celery.py", line 837, in load_extension_commands
    self.register_command).load()
  File "/apps/python/http_runner/lib/python3.6/site-packages/celery/bin/base.py", line 155, in load
    cls = symbol_by_name(sym)
  File "/apps/python/http_runner/lib/python3.6/site-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/apps/python/http_runner/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/apps/python/http_runner/lib/python3.6/site-packages/flower/command.py", line 18, in <module>
    from .app import Flower
  File "/apps/python/http_runner/lib/python3.6/site-packages/flower/app.py", line 15, in <module>
    from .urls import handlers
  File "/apps/python/http_runner/lib/python3.6/site-packages/flower/urls.py", line 9, in <module>
    from .api import tasks
  File "/apps/python/http_runner/lib/python3.6/site-packages/flower/api/tasks.py", line 81, in <module>
    class TaskApply(BaseTaskHandler):
  File "/apps/python/http_runner/lib/python3.6/site-packages/flower/api/tasks.py", line 83, in TaskApply
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

**Comment by xuanyuexx** [comment]
请问您解决这个问题了吗？是启用异步 worker的时候遇到的吗？

**Comment by asdf2014** [comment]
@xuanyuexx 执行的 `python manage.py celery -A HttpRunnerManager worker --loglevel=info` 这个命令触发的

**Comment by xuanyuexx** [comment]
我的也是，我是3月19日下载的HttpRunnerManager 昨天执行这个命令也报的这个错误，您现在解决了吗

**Comment by asdf2014** [comment]
@xuanyuexx 并没有，，
