### ISSUE TITLE
python manage.py celery -A HttpRunnerManager worker --logle vel=info报错AttributeError: module 'tornado.web' has no attribute 'asynchronous'

### ISSUE THREAD

**Issue by xuanyuexx** [HttpRunner/HttpRunnerManager#137]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>d:

D:\>cd httprunnermanager

D:\HttpRunnerManager>python manage.py celery -A HttpRunnerManager worker --logle
vel=info
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\django\core\management\__init__.py", line 371, in execute_from_comman
d_line
    utility.execute()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\djcelery\management\commands\celery.py", line 21, in run_from_argv
    ['{0[0]} {0[1]}'.format(argv)] + argv[2:],
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\celery\bin\celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\celery\bin\base.py", line 305, in execute_from_commandline
    self.on_concurrency_setup()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\celery\bin\celery.py", line 833, in on_concurrency_setup
    self.load_extension_commands()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\celery\bin\celery.py", line 837, in load_extension_commands
    self.register_command).load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\celery\bin\base.py", line 155, in load
    cls = symbol_by_name(sym)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\kombu\utils\__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\imp
ortlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\flower\command.py", line 18, in <module>
    from .app import Flower
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\flower\app.py", line 15, in <module>
    from .urls import handlers
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\flower\urls.py", line 9, in <module>
    from .api import tasks
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\flower\api\tasks.py", line 81, in <module>
    class TaskApply(BaseTaskHandler):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\flower\api\tasks.py", line 83, in TaskApply
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

D:\HttpRunnerManager>

**Comment by imath60** [comment]
因tornado在6.0.0版本删除了asynchronous装饰器导致，请在requirement.txt文件添加配置安装tornado 5.1.1版本
tornado>=4.2.0,<6.0.0
![image](https://user-images.githubusercontent.com/6263682/55219826-dbc4c080-5240-11e9-89a9-14faaee5e287.png)

**Comment by xuanyuexx** [comment]
非常感谢，通过您上面的方法，解决了
