### ISSUE TITLE
#启动worker报错

### ISSUE THREAD

**Issue by bzc128** [HttpRunner/HttpRunnerManager#140]
C:\Users\Administrator\PycharmProjects\HttpRunnerManager-master>python manage.py celery -A HttpRunnerManager worker --loglevel=info
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_co
mmand_line
    utility.execute()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\djcelery\management\commands\celery.py", line 21, in run_from_arg
v
    ['{0[0]} {0[1]}'.format(argv)] + argv[2:],
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\celery\bin\celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\celery\bin\base.py", line 305, in execute_from_commandline
    self.on_concurrency_setup()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\celery\bin\celery.py", line 833, in on_concurrency_setup
    self.load_extension_commands()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\celery\bin\celery.py", line 837, in load_extension_commands
    self.register_command).load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\celery\bin\base.py", line 155, in load
    cls = symbol_by_name(sym)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\kombu\utils\__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\flower\command.py", line 18, in <module>
    from .app import Flower
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\flower\app.py", line 15, in <module>
    from .urls import handlers
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\flower\urls.py", line 9, in <module>
    from .api import tasks
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\flower\api\tasks.py", line 81, in <module>
    class TaskApply(BaseTaskHandler):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\flower\api\tasks.py", line 83, in TaskApply
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

**Comment by imath60** [comment]
> C:\Users\Administrator\PycharmProjects\HttpRunnerManager-master>python manage.py celery -A HttpRunnerManager worker --loglevel=info
> Traceback (most recent call last):
> File "manage.py", line 22, in 
> execute_from_command_line(sys.argv)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management__init__.py", line 371, in execute_from_co
> mmand_line
> utility.execute()
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management__init__.py", line 365, in execute
> self.fetch_command(subcommand).run_from_argv(self.argv)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\djcelery\management\commands\celery.py", line 21, in run_from_arg
> v
> ['{0[0]} {0[1]}'.format(argv)] + argv[2:],
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\celery\bin\celery.py", line 793, in execute_from_commandline
> super(CeleryCommand, self).execute_from_commandline(argv)))
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\celery\bin\base.py", line 305, in execute_from_commandline
> self.on_concurrency_setup()
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\celery\bin\celery.py", line 833, in on_concurrency_setup
> self.load_extension_commands()
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\celery\bin\celery.py", line 837, in load_extension_commands
> self.register_command).load()
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\celery\bin\base.py", line 155, in load
> cls = symbol_by_name(sym)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\kombu\utils__init__.py", line 96, in symbol_by_name
> module = imp(module_name, package=package, **kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\importlib__init__.py", line 126, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 994, in _gcd_import
> File "", line 971, in _find_and_load
> File "", line 955, in _find_and_load_unlocked
> File "", line 665, in _load_unlocked
> File "", line 678, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\flower\command.py", line 18, in 
> from .app import Flower
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\flower\app.py", line 15, in 
> from .urls import handlers
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\flower\urls.py", line 9, in 
> from .api import tasks
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\flower\api\tasks.py", line 81, in 
> class TaskApply(BaseTaskHandler):
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\flower\api\tasks.py", line 83, in TaskApply
> @web.asynchronous
> AttributeError: module 'tornado.web' has no attribute 'asynchronous'

因tornado在6.0.0版本删除了asynchronous装饰器导致，请在requirement.txt文件添加配置安装tornado 5.1.1版本
tornado>=4.2.0,<6.0.0
![image](https://user-images.githubusercontent.com/6263682/55219914-06af1480-5241-11e9-8fcd-c2dcf3072650.png)
