### ISSUE TITLE
下载了master代码，运行用例时报错

### ISSUE THREAD

**Issue by zhouwei713** [HttpRunner/HttpRunnerManager#150]
![image](https://user-images.githubusercontent.com/12554051/57294190-75fa0d00-70f9-11e9-9564-d0cc57c7bb11.png)

ERROR:django.request:Internal Server Error: /api/run_test/
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/file/zhouwei/httprunner/HttpRunnerManager-master/HttpRunnerManager/activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "/file/zhouwei/httprunner/HttpRunnerManager-master/ApiManager/views.py", line 39, in wrapper
    return func(request, *args, **kwargs)
  File "/file/zhouwei/httprunner/HttpRunnerManager-master/ApiManager/views.py", line 236, in run_test
    runner.run(testcase_dir_path)
  File "/usr/local/python/lib/python3.6/site-packages/httprunner/task.py", line 238, in run
    test_suite_list = init_test_suites(path_or_testsets, mapping)
  File "/usr/local/python/lib/python3.6/site-packages/httprunner/task.py", line 184, in init_test_suites
    testsets = TestcaseLoader.load_testsets_by_path(path_or_testsets)
  File "/usr/local/python/lib/python3.6/site-packages/httprunner/testcase.py", line 375, in load_testsets_by_path
    testcases_list = TestcaseLoader.load_testsets_by_path(files_list)
  File "/usr/local/python/lib/python3.6/site-packages/httprunner/testcase.py", line 360, in load_testsets_by_path
    testset = TestcaseLoader.load_testsets_by_path(file_path)
  File "/usr/local/python/lib/python3.6/site-packages/httprunner/testcase.py", line 380, in load_testsets_by_path
    if testset["testcases"] or testset["api"]:
KeyError: 'api'
2019-05-07 18:50:13,267 [django.server:124] [basehttp:log_message] [ERROR]- "POST /api/run_test/ HTTP/1.1" 500 100062
ERROR:django.server:"POST /api/run_test/ HTTP/1.1" 500 100062

**Comment by zhouwei713** [comment]
是我用例的url字段没有填，这里做个限制更好吧
