### ISSUE TITLE
执行python manage.py makemigrations ApiManager  这个时，报没有数据库httprunner，实际我已经创建好了

### ISSUE THREAD

**Issue by baoshd** [HttpRunner/HttpRunnerManager#46]
执行python manage.py makemigrations ApiManager  这个时，报没有数据库httprunner；实际我已经创建好了。

D:\github\HttpRunnerManager>python manage.py makemigrations ApiManager
Traceback (most recent call last):
  File "D:\application\Python\Python36-32\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "D:\application\Python\Python36-32\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\application\Python\Python36-32\lib\site-packages\django\db\backends\mysql\base.py", line 236, in get_new_connection
    return Database.connect(**conn_params)
  File "D:\application\Python\Python36-32\lib\site-packages\MySQLdb\__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "D:\application\Python\Python36-32\lib\site-packages\MySQLdb\connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1049, "Unknown database 'httprunner'")

**Comment by yinquanwang** [comment]
确认建好了?

**Comment by baoshd** [comment]
@yinquanwang 自己失误，大小写的问题。
