### ISSUE TITLE
创建case时无法读取项目下的模块列表

### ISSUE THREAD

**Issue by yileye** [HttpRunner/HttpRunnerManager#5]
![image](https://user-images.githubusercontent.com/12822671/36714122-cde27fa4-1bcb-11e8-9307-1efcb4844962.png)

def add_case(request):
    project = ProjectInfo.objects.all().values('pro_name').order_by('create_time')
    print(project)
    if request.is_ajax():
        testcase_lists = json.loads(request.body.decode('utf-8'))
        msg = case_info_logic(**testcase_lists)
        return HttpResponse(get_ajax_msg(msg, '用例添加成功'))
    elif request.method == 'GET':
        return render_to_response('add_case.html', {'project': project})

定位到这段代码，应该是没有用外键去查询项目对应的模块信息

**Comment by yinquanwang** [comment]
你好，这个bug一直都存在，我忘记改了，这是因为前端用的onchange出发ajax异步请求，当只有一个项目存在时不会和后端交互，须两个项目以上才行，稍后就会修复，多谢支持

**Comment by yinquanwang** [comment]
你好，此bug已修复，麻烦整体更新下代码重新验证下

**Comment by yileye** [comment]
还不行，因为在拉取模块列表的时候直接报错了 ，而且在页面上也没有绑定模块列表的数据

Internal Server Error: /api/add_case/
Traceback (most recent call last):
  File "/Users/finup/gitlab/HttpRunnerManager-master/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/finup/gitlab/HttpRunnerManager-master/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/finup/gitlab/HttpRunnerManager-master/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/finup/gitlab/HttpRunnerManager-master/HttpRunnerManager/activator.py", line 23, in process
    result = fun(request)
  File "/Users/finup/gitlab/HttpRunnerManager-master/ApiManager/views.py", line 62, in add_case
    testcase_lists = json.loads(request.body.decode('utf-8'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[27/Feb/2018 15:23:23] "GET /api/add_case/ HTTP/1.1" 500 15144


![image](https://user-images.githubusercontent.com/12822671/36716436-514417be-1bd5-11e8-8d04-3cf311448070.png)

**Comment by yinquanwang** [comment]
没明白你的意思？我这边已经测试过了没问题了，你的意思是页面点击时拉取模块数据后台报错了？

**Comment by yileye** [comment]
对的，是的，后台报错了

**Comment by yinquanwang** [comment]
时候可以提供下qq，我远程看下？这样我看不出什么问题，毕竟我本地测试没发现这个现象

**Comment by yileye** [comment]
可以
![image](https://user-images.githubusercontent.com/12822671/36717103-b5a86834-1bd7-11e8-8baf-e67fd9a1e524.png)

**Comment by yinquanwang** [comment]
@yileye 是什么原因呢？代码有bug么？有的话我这边修复下

**Comment by yileye** [comment]
QQ在回复里了，你可以添加一下

**Comment by yinquanwang** [comment]
已经加了，你看下qq验证消息
